### ISSUE TITLE
error calling Paginate: 'pager size' must be a positive integer

### ISSUE THREAD

**Issue by c0b** [djuelg/Shapez-Theme#6]
with hugo version `Hugo Static Site Generator v0.16 BuildDate: 2016-06-06T05:31:27-07:00` a fresh new site just created with `hugo new site`

```
ERROR: 2016/08/21 13:27:05 general.go:222: Error while rendering homepage: template: 
theme/index.html:27:29: executing "theme/index.html" at <.Paginate>:
error calling Paginate: 'pager size' must be a positive integer
```

**Comment by djuelg** [comment]
Sorry, I had no time to test the theme with v0.16 yet. I will look through this bug during next month. Please let me know if you fix it by yourself :)

**Comment by djuelg** [comment]
I couldn't reproduce your error.
The theme seems to be working fine with v0.16 of gohugo

**Comment by djuelg** [comment]
Reproduced and fixed with #9

**Comment by djuelg** [comment]
#9
